# Numpy with Jadi
- fifth lesson from machine learning

In [5]:
import numpy as np

## lets do some basic stuff

In [8]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
print(a.shape)
print(a.ndim)
print(a.size)
a.dtype

(3, 5)
2
15


dtype('int32')

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## some operations

In [24]:
b = np.array([20, 30, 40, 50])
c = np.arange(4)

In [28]:
print(b)
print(c)
print(b + c)
print(b - c)
print(b * c)

[20 30 40 50]
[0 1 2 3]
[20 31 42 53]
[20 29 38 47]
[  0  30  80 150]
